### ISSUE TITLE
Not working with oneplus , TEE broken devices 

### ISSUE THREAD

**Issue by khalidaboelmagd** [swer45/AttestationSpoofer#1]
Hi ,

Thanks for your work, I've oneplus 7 pro 
the TEE is broken and the spoofer isn't working.

can you modify it, I can test for you if you want device to test on

**Comment by swer45** [comment]
If your device doesn't support hardware attestation it's not possible to spoof a locked bootloader. Maybe injecting a fake X509Certificate would be possible but I would need to investigate about that.

**Comment by sudanking** [comment]
Thanks for this great effort...
I have the same problem, oneplus 7 pro with TEE broken.
How to know if our device support hw attestation?
And is there is a solution to inject this X509 certificate?
