### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by xAffan** [swer45/AttestationSpoofer#2]
Hello, I want to contact you and pay u for strong integrity bypass (strictly for personal use) i just have a few issues with banking which I really want to get fixed

**Comment by swer45** [comment]
I don't yet have the knowledge to see how I could do a Strong bypass. However, some of the ROMs on xiaomi.eu pass the Strong, I think I know how they did it but I'm not sure. If I get something maybe I'll make an Xposed or Zygisk module.
https://forum.xda-developers.com/t/xposed-attestationspoofer.4586251/post-88545625
